apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "portainer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: {{ include "portainer.fullname" . }}
             port:
               number: 9000
    host: portainer.acf0f57a-13bc-445f-bcc8-938375a6a264.k8s.civo.com
