
grafana:
  enabled: true
  grafana:
    service:
      type: LoadBalancer
      port: 3000
    persistence:
      storageClass: "local-path"
      size: 10Gi
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
