
grafana:
  enabled: true
  admin:
    existingSecret: "grafana-password"
  replicaCount: 1
  updateStrategy:
    type: Recreate
  service:
    type: LoadBalancer
    port: 3000
  persistence:
    storageClass: "civo-volume"
    accessMode: ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
