fullnameOverride: wolke7-infra-portainer

portainer:
  enabled: true
  replicaCount: 2
  image.tag: "2.1.1"
  resources: 
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  service:
    type: LoadBalancer
    httpPort: 9000
  persistence:
    # existingClaim: pvc-portainer
    accessModes: ReadWriteMany
    storageClass: civo-volume
    size: "10Gi"

# env:
#  DNS: portainer
  # valueFrom:
  #   configMapRef:
  #     name: cluster-vars
  #     key: DNS
