fullnameOverride: wolke7-infra-portainer
DNS: 58bfc6fc-8830-4bbe-b64b-45e77d7fb0ca.k8s.civo.com
portainer:
  enabled: true
  replicaCount: 3
  image.tag: "2.1.1"
  resources: 
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  # service:
  #   type: LoadBalancer
  #   httpPort: 80
  persistence:
    # existingClaim: pvc-portainer
    accessModes: ReadWriteOnce
    # storageClass: local-path
    size: "3Gi"

